name: 'mergify-merge-queue-labels-copier'
description: 'Mergify: copies pull request labels to merge queue draft PRs'
branding:
  icon: arrow-up
  color: 'blue'
inputs:
  labels:
    description: 'Comma separated list of labels to copy (all if empty)'
    required: true
    default: ''
  additional-labels:
    description: 'Comma separated list of additional labels to add to the merge queue PR'
    required: false
    default: ''
  token:
    description: 'The GitHub token to use for API requests'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Copying labels
      shell: bash
      if: startsWith(github.head_ref, 'mergify/merge-queue/')
      env:
        REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        MERGE_QUEUE_PR_URL: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
        GH_TOKEN: ${{ inputs.token }}
        GH_ENTERPRISE_TOKEN: ${{ inputs.token }}
        LABELS_TO_COPY: ${{ inputs.labels }}
        ADDITIONAL_LABELS: ${{ inputs.additional-labels }}
      run: ./run.sh
